version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - zip -g deployment_package_LambdaProcessFilteredBookings.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_LambdaProcessFilteredBookings.zip s3://lambda-builds-zip-sm/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name lambdaProcessFilteredBookings --s3-bucket lambda-builds-zip-sm --s3-key deployment_package_LambdaProcessFilteredBookings.zip
      - echo "Deployment complete!"